FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app


RUN apt-get update \
    && apt-get install -y \
        --no-install-recommends \
        gcc \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*


COPY document_service/requirements.txt \
    ./document_service/requirements.txt


RUN pip install --upgrade pip \
    && pip install --no-cache-dir \
        -r document_service/requirements.txt


COPY document_service ./document_service


CMD ["uvicorn", "document_service.main:app", "--host", "0.0.0.0", "--port", "8001"]