FROM postgres:18-alpine

COPY docker/postgres/seed/business_platform.dump \
    /docker-entrypoint-initdb.d/business_platform.dump

COPY docker/postgres/init/01-restore-database.sh \
    /docker-entrypoint-initdb.d/01-restore-database.sh

RUN chmod +x \
    /docker-entrypoint-initdb.d/01-restore-database.sh