"""create initial tables

Revision ID: 50eb5bb4550f
Revises: 
Create Date: 2026-08-22 14:52:43.766259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50eb5bb4550f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('business_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_business_id'), 'businesses', ['business_id'], unique=True)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('documents',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', 'VIEWER', name='user_role_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('business_category',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id', 'category_id', 'id')
    )
    op.create_table('mentions',
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('REVIEW', name='source_type,enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('resolved_business_id', sa.Integer(), nullable=True),
    sa.Column('resolution_status', sa.Enum('PENDING', 'AUTO_RESOLVED', 'SENT_FOR_REVIEWER', 'APPROVED', 'REJECTED', name='resolution_status_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='ck_mention_confidence_range'),
    sa.ForeignKeyConstraint(['resolved_business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentions_resolution_status'), 'mentions', ['resolution_status'], unique=False)
    op.create_index(op.f('ix_mentions_resolved_business_id'), 'mentions', ['resolved_business_id'], unique=False)
    op.create_index(op.f('ix_mentions_source_id'), 'mentions', ['source_id'], unique=False)
    op.create_table('resolution_results',
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('AUTO', 'REVIEW', 'APPROVED', 'REJECTED', name='resolution_decision_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 1', name='ck_resolution_score_range'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolution_results_business_id'), 'resolution_results', ['business_id'], unique=False)
    op.create_index(op.f('ix_resolution_results_decision'), 'resolution_results', ['decision'], unique=False)
    op.create_index(op.f('ix_resolution_results_mention_id'), 'resolution_results', ['mention_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolution_results_mention_id'), table_name='resolution_results')
    op.drop_index(op.f('ix_resolution_results_decision'), table_name='resolution_results')
    op.drop_index(op.f('ix_resolution_results_business_id'), table_name='resolution_results')
    op.drop_table('resolution_results')
    op.drop_index(op.f('ix_mentions_source_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_resolved_business_id'), table_name='mentions')
    op.drop_index(op.f('ix_mentions_resolution_status'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_table('business_category')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('documents')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
