"""changes in syntax

Revision ID: ef2d19e8718e
Revises: 50eb5bb4550f
Create Date: 2026-08-22 15:31:16.306501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2d19e8718e'
down_revision: Union[str, Sequence[str], None] = '50eb5bb4550f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('resolution_status_enum'), 'mentions', type_='check')
    op.drop_constraint(op.f('source_type,enum'), 'mentions', type_='check')
    op.drop_constraint(op.f('resolution_decision_enum'), 'resolution_results', type_='check')
    op.drop_constraint(op.f('user_role_enum'), 'users', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('user_role_enum'), 'users', "role::text = ANY (ARRAY['ADMIN'::character varying, 'REVIEWER'::character varying, 'VIEWER'::character varying]::text[])")
    op.create_check_constraint(op.f('resolution_decision_enum'), 'resolution_results', "decision::text = ANY (ARRAY['AUTO'::character varying, 'REVIEW'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying]::text[])")
    op.create_check_constraint(op.f('source_type,enum'), 'mentions', "source_type::text = 'REVIEW'::text")
    op.create_check_constraint(op.f('resolution_status_enum'), 'mentions', "resolution_status::text = ANY (ARRAY['PENDING'::character varying, 'AUTO_RESOLVED'::character varying, 'SENT_FOR_REVIEWER'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying]::text[])")
    # ### end Alembic commands ###
